set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-shell /bin/zsh
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
setw -g automatic-rename on  # Автоматически переименовывать окна


# Use Alt-arrow keys without prefix key to switch panes
bind -n C-S-Left select-pane -L
bind -n C-S-Right select-pane -R
bind -n C-S-Up select-pane -U
bind -n C-S-Down select-pane -D

# Shift arrow to switch windows
bind -n C-M-Left  previous-window
bind -n C-M-Right next-window

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'
set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
#set -g @plugin 'erikw/tmux-powerline'
#set -g @plugin 'thewtex/tmux-mem-cpu-load'
run '~/.config/tmux/plugins/tpm/tpm'


# Bind-keys TEST
bind-key -n C-t new-window
bind-key -n C-w kill-window

#Split Windows
bind-key -n C-p split-window -h -c "#{pane_current_path}"
bind-key -n C-l break-pane 
bind-key -n M-l kill-pane
bind-key -n C-h split-window -v -c "#{pane_current_path}"
# По умолчанию тёмная тема
source-file ~/.config/tmux/themes/dracula.conf

# F7 = 'n' только если в панели сейчас запущен nnn, иначе отдать F7 приложению
# --- F-keys act like nnn keys ONLY when nnn is the running command in the pane ---
bind-key -n F2 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys C-r' 'send-keys F2'
bind-key -n F4 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys e'   'send-keys F4'
bind-key -n F5 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys p'   'send-keys F5'
bind-key -n F6 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys v'   'send-keys F6'
bind-key -n F7 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys n'   'send-keys F7'
bind-key -n F8 if-shell -F '#{==:#{pane_current_command},nnn}' 'send-keys X'   'send-keys F8'


